/**
 * 鱼类属性配置
 * 所有鱼种数值由配置驱动
 */
export const FishConfig = {
    // ===== 鱼类定义 =====
    types: {
        goldfish: {
            id: 'goldfish',
            name: '彩色金鱼',
            score: 10,
            hp: 1,
            speed: 120,
            size: 36,
            boneSegments: 5,
            spineSegments: 8,               // 脊椎骨骼节数（升级后最小8节）
            fresnelIntensity: 0.12,         // 菲涅尔反射 F0
            scaleType: 'cycloid',            // 鳞片类型 cycloid/ctenoid/ganoid/dragon
            spawnWeight: 30,
            color: '#FF8C42',
            accentColor: '#FFD700',
            finColor: '#FF6B6B',
            pathType: 'sine',              // 直线/正弦/环形/随机
            schoolFish: true,               // 是否结群
            schoolSize: [5, 12],            // 鱼群大小范围
            depth: 'near',                  // 景深层级 near/mid/far
            imagePath: 'assets/fish/goldfish.png',  // 鱼类图片路径
            spawnDirections: ['left', 'right', 'top', 'bottom'], // 出现方向偏好
            speedRange: [80, 150]           // 生成速度范围 [min, max]
        },
        silverfish: {
            id: 'silverfish',
            name: '小银鱼',
            score: 5,
            hp: 1,
            speed: 180,
            size: 28,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 30,
            color: '#C0D8E8',
            accentColor: '#E8F4FF',
            finColor: '#A8C8E0',
            pathType: 'linear',
            schoolFish: true,
            schoolSize: [8, 20],
            depth: 'mid',
            imagePath: 'assets/fish/silverfish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [120, 220]
        },
        turtle: {
            id: 'turtle',
            name: '灵龟',
            score: 50,
            hp: 3,
            speed: 60,
            size: 56,
            boneSegments: 6,
            spineSegments: 9,
            fresnelIntensity: 0.15,
            scaleType: 'ganoid',
            spawnWeight: 15,
            color: '#2D8B5E',
            accentColor: '#4ADE80',
            finColor: '#1E6B42',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/turtle.png',
            spawnDirections: ['left', 'right'],
            speedRange: [40, 80]
        },
        manta: {
            id: 'manta',
            name: '蝠鲼',
            score: 80,
            hp: 4,
            speed: 100,
            size: 72,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.12,
            scaleType: 'ctenoid',
            spawnWeight: 12,
            color: '#4A5568',
            accentColor: '#718096',
            finColor: '#2D3748',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/manta.png',
            imageScale: 2.0,                 // 宽扁鱼，放大贴图避免翼展被裁剪
            spawnDirections: ['left', 'right'],
            speedRange: [70, 130]
        },
        jellyfish: {
            id: 'jellyfish',
            name: '幻彩水母',
            score: 60,
            hp: 2,
            speed: 40,
            size: 48,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.08,
            scaleType: 'cycloid',
            spawnWeight: 14,
            color: '#FF69B4',
            accentColor: '#FFB6C1',
            finColor: '#DA70D6',
            pathType: 'float',
            schoolFish: true,
            schoolSize: [2, 5],
            depth: 'mid',
            glow: true,
            imagePath: 'assets/fish/jellyfish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [25, 55]
        },
        seahorse: {
            id: 'seahorse',
            name: '珊瑚海马',
            score: 30,
            hp: 2,
            speed: 90,
            size: 32,
            boneSegments: 5,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'ctenoid',
            spawnWeight: 18,
            color: '#FF8C00',
            accentColor: '#FFD700',
            finColor: '#FF6347',
            pathType: 'erratic',
            schoolFish: true,
            schoolSize: [3, 8],
            depth: 'near',
            imagePath: 'assets/fish/seahorse.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [60, 120]
        },
        anglerfish: {
            id: 'anglerfish',
            name: '深海灯笼鱼',
            score: 150,
            hp: 6,
            speed: 55,
            size: 64,
            boneSegments: 5,
            spineSegments: 10,
            fresnelIntensity: 0.15,
            scaleType: 'ctenoid',
            spawnWeight: 8,
            color: '#2C1810',
            accentColor: '#8B4513',
            finColor: '#1A0F0A',
            pathType: 'random',
            schoolFish: false,
            depth: 'far',
            glow: true,
            lureColor: '#00FF7F',
            imagePath: 'assets/fish/anglerfish.png',
            imageScale: 2.0,                 // 宽扁鱼，放大贴图避免触须/吻部被裁剪
            spawnDirections: ['left', 'right'],
            speedRange: [40, 75]
        },
        blackdragon: {
            id: 'blackdragon',
            name: '黑龙',
            score: 200,
            hp: 8,
            speed: 90,
            size: 90,
            boneSegments: 8,
            spineSegments: 11,
            fresnelIntensity: 0.20,
            scaleType: 'dragon',
            spawnWeight: 8,
            color: '#1A1A2E',
            accentColor: '#6B5B95',
            finColor: '#3D2E5C',
            pathType: 'sine',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/blackdragon.png',
            imageScale: 2.2,                 // 长鱼，放大贴图避免长尾/龙身被裁剪
            spawnDirections: ['left', 'right'],
            speedRange: [60, 120]
        },
        goldendragon: {
            id: 'goldendragon',
            name: '黄金龙鱼',
            score: 500,
            hp: 12,
            speed: 70,
            size: 100,
            boneSegments: 8,
            spineSegments: 12,
            fresnelIntensity: 0.30,        // 金龙鱼强菲涅尔 F0=0.3
            scaleType: 'dragon',
            spawnWeight: 4,
            color: '#DAA520',
            accentColor: '#FFD700',
            finColor: '#B8860B',
            pathType: 'circle',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/goldendragon.png',
            imageScale: 2.2,                 // 长鱼，放大贴图避免长尾/龙身被裁剪
            spawnDirections: ['left', 'right'],
            speedRange: [50, 90]
        },
        dragonking: {
            id: 'dragonking',
            name: '中国金龙',
            score: 30000,
            hp: 15000,
            speed: 20,
            size: 350,
            boneSegments: 12,
            spineSegments: 14,
            fresnelIntensity: 0.40,
            scaleType: 'dragon',
            spawnWeight: 1,
            color: '#DAA520',
            accentColor: '#FFD700',
            finColor: '#B8860B',
            pathType: 'boss',
            schoolFish: false,
            isBoss: true,
            depth: 'far',
            glow: true,
            glowColor: '#FFD700',
            bossWarningDuration: 3,       // BOSS 出场预警时长（秒）
            bossDisperseRadius: 500,      // BOSS 驱散小鱼半径
            imagePath: 'assets/fish/boss-golden-dragon.png',
            imageScale: 2.8,                // BOSS完整S形龙身，略缩小确保从头到尾完整可见
            spawnDirections: ['top', 'right'],
            speedRange: [35, 55]
        },
        // ===== 特殊鱼类 =====
        electriceel: {
            id: 'electriceel',
            name: '雷电鳗',
            score: 120,
            hp: 3,
            speed: 100,
            size: 55,
            boneSegments: 8,
            spineSegments: 10,
            fresnelIntensity: 0.12,
            scaleType: 'ctenoid',
            spawnWeight: 6,
            color: '#4A0080',
            accentColor: '#00FFFF',
            finColor: '#9400D3',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            special: 'electric',           // 特殊行为：电击
            glow: true,
            glowColor: '#00FFFF',
            imagePath: 'assets/fish/electriceel.png',
            imageScale: 2.2,                 // 长鱼，放大贴图避免鳗身被裁剪
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [70, 130]
        },
        ghostfish: {
            id: 'ghostfish',
            name: '幽灵鱼',
            score: 180,
            hp: 2,
            speed: 90,
            size: 48,
            boneSegments: 6,
            spineSegments: 9,
            fresnelIntensity: 0.08,
            scaleType: 'cycloid',
            spawnWeight: 5,
            color: '#E8E8FF',
            accentColor: '#B8B8FF',
            finColor: '#D0D0FF',
            pathType: 'erratic',
            schoolFish: false,
            depth: 'mid',
            special: 'invisible',          // 特殊行为：隐身
            glow: true,
            glowColor: '#E8E8FF',
            imagePath: 'assets/fish/ghostfish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [60, 120]
        },
        splitfish: {
            id: 'splitfish',
            name: '分裂水母',
            score: 90,
            hp: 2,
            speed: 70,
            size: 50,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 7,
            color: '#FF69B4',
            accentColor: '#FFB6C1',
            finColor: '#FF1493',
            pathType: 'float',
            schoolFish: false,
            depth: 'near',
            special: 'split',              // 特殊行为：分裂
            glow: true,
            glowColor: '#FF69B4',
            imagePath: 'assets/fish/splitfish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [50, 90]
        },

        // ===== 新增生态鱼类（丰富鱼群多样性） =====
        clownfish: {
            id: 'clownfish',
            name: '小丑鱼',
            score: 15,
            hp: 1,
            speed: 130,
            size: 30,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 28,
            color: '#FF7A00',
            accentColor: '#FFD700',
            finColor: '#FFFFFF',
            pathType: 'sine',
            schoolFish: true,
            schoolSize: [6, 14],
            depth: 'near',
            imagePath: 'assets/fish/clownfish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [90, 160]
        },
        guppy: {
            id: 'guppy',
            name: '孔雀鱼',
            score: 8,
            hp: 1,
            speed: 150,
            size: 24,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 30,
            color: '#2E9BE6',
            accentColor: '#FF6FB5',
            finColor: '#7DF9FF',
            pathType: 'linear',
            schoolFish: true,
            schoolSize: [8, 18],
            depth: 'mid',
            imagePath: 'assets/fish/guppy.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [110, 180]
        },
        zebrafish: {
            id: 'zebrafish',
            name: '斑马鱼',
            score: 12,
            hp: 1,
            speed: 140,
            size: 28,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 26,
            color: '#E8F4FF',
            accentColor: '#3A6EA5',
            finColor: '#9CC0E8',
            pathType: 'sine',
            schoolFish: true,
            schoolSize: [6, 16],
            depth: 'near',
            imagePath: 'assets/fish/zebrafish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [100, 170]
        },
        neonfish: {
            id: 'neonfish',
            name: '霓虹灯鱼',
            score: 20,
            hp: 1,
            speed: 120,
            size: 26,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 22,
            color: '#1A6FE0',
            accentColor: '#00E5FF',
            finColor: '#FF3B6B',
            pathType: 'float',
            schoolFish: true,
            schoolSize: [8, 18],
            depth: 'mid',
            glow: true,
            glowColor: '#00E5FF',
            imagePath: 'assets/fish/neonfish.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [80, 140]
        },
        pufferfish: {
            id: 'pufferfish',
            name: '河豚',
            score: 40,
            hp: 3,
            speed: 70,
            size: 44,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'ctenoid',
            spawnWeight: 14,
            color: '#D9C84A',
            accentColor: '#F0E68C',
            finColor: '#B89E3A',
            pathType: 'erratic',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/pufferfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [45, 90]
        },
        octopus: {
            id: 'octopus',
            name: '章鱼',
            score: 100,
            hp: 5,
            speed: 60,
            size: 60,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 10,
            color: '#8E44AD',
            accentColor: '#BB8FCE',
            finColor: '#6C3483',
            pathType: 'random',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/octopus.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [40, 80]
        },
        squid: {
            id: 'squid',
            name: '鱿鱼',
            score: 70,
            hp: 3,
            speed: 110,
            size: 50,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 12,
            color: '#5D6D7E',
            accentColor: '#AED6F1',
            finColor: '#34495E',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/squid.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [80, 140]
        },
        shark: {
            id: 'shark',
            name: '鲨鱼',
            score: 300,
            hp: 10,
            speed: 140,
            size: 90,
            boneSegments: 7,
            spineSegments: 11,
            fresnelIntensity: 0.18,
            scaleType: 'ctenoid',
            spawnWeight: 6,
            color: '#5D6D7E',
            accentColor: '#85929E',
            finColor: '#2C3E50',
            pathType: 'linear',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/shark.png',
            spawnDirections: ['left', 'right'],
            speedRange: [100, 180]
        },
        swordfish: {
            id: 'swordfish',
            name: '旗鱼',
            score: 250,
            hp: 8,
            speed: 180,
            size: 85,
            boneSegments: 7,
            spineSegments: 11,
            fresnelIntensity: 0.18,
            scaleType: 'ctenoid',
            spawnWeight: 6,
            color: '#1F618D',
            accentColor: '#5DADE2',
            finColor: '#154360',
            pathType: 'linear',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/swordfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [140, 220]
        },
        tuna: {
            id: 'tuna',
            name: '金枪鱼',
            score: 200,
            hp: 7,
            speed: 160,
            size: 80,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.15,
            scaleType: 'ctenoid',
            spawnWeight: 7,
            color: '#21618C',
            accentColor: '#AAB7C4',
            finColor: '#154360',
            pathType: 'circle',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/tuna.png',
            spawnDirections: ['left', 'right'],
            speedRange: [120, 200]
        },
        grouper: {
            id: 'grouper',
            name: '石斑鱼',
            score: 180,
            hp: 6,
            speed: 80,
            size: 75,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.15,
            scaleType: 'ctenoid',
            spawnWeight: 8,
            color: '#7D6608',
            accentColor: '#D4AC0D',
            finColor: '#5B4A06',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/grouper.png',
            spawnDirections: ['left', 'right'],
            speedRange: [55, 100]
        },
        discus: {
            id: 'discus',
            name: '七彩神仙鱼',
            score: 60,
            hp: 2,
            speed: 80,
            size: 40,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 14,
            color: '#E67E22',
            accentColor: '#F1948A',
            finColor: '#922B21',
            pathType: 'float',
            schoolFish: true,
            schoolSize: [3, 8],
            depth: 'near',
            imagePath: 'assets/fish/discus.png',
            spawnDirections: ['left', 'right', 'top', 'bottom'],
            speedRange: [55, 100]
        },
        lobster: {
            id: 'lobster',
            name: '龙虾',
            score: 150,
            hp: 5,
            speed: 50,
            size: 55,
            boneSegments: 6,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'ganoid',
            spawnWeight: 9,
            color: '#C0392B',
            accentColor: '#F1948A',
            finColor: '#7B241C',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/lobster.png',
            spawnDirections: ['left', 'right'],
            speedRange: [35, 65]
        },
        crab: {
            id: 'crab',
            name: '螃蟹',
            score: 80,
            hp: 3,
            speed: 40,
            size: 45,
            boneSegments: 5,
            spineSegments: 8,
            fresnelIntensity: 0.12,
            scaleType: 'ganoid',
            spawnWeight: 11,
            color: '#A93226',
            accentColor: '#EC7063',
            finColor: '#641E16',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/crab.png',
            spawnDirections: ['left', 'right'],
            speedRange: [28, 52]
        },
        starfish: {
            id: 'starfish',
            name: '海星',
            score: 35,
            hp: 2,
            speed: 20,
            size: 35,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 16,
            color: '#E59866',
            accentColor: '#F8C471',
            finColor: '#CA6F1E',
            pathType: 'float',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/starfish.png',
            spawnDirections: ['top', 'bottom'],
            speedRange: [12, 30]
        },
        dolphin: {
            id: 'dolphin',
            name: '海豚',
            score: 400,
            hp: 12,
            speed: 150,
            size: 100,
            boneSegments: 7,
            spineSegments: 11,
            fresnelIntensity: 0.18,
            scaleType: 'ctenoid',
            spawnWeight: 3,                  // 稀有
            color: '#5D8AA8',
            accentColor: '#AEB6BF',
            finColor: '#34495E',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/dolphin.png',
            spawnDirections: ['left', 'right'],
            speedRange: [110, 190]
        },
        whale: {
            id: 'whale',
            name: '鲸鱼',
            score: 800,
            hp: 20,
            speed: 60,
            size: 140,
            boneSegments: 8,
            spineSegments: 12,
            fresnelIntensity: 0.22,
            scaleType: 'ctenoid',
            spawnWeight: 1,                  // 极稀有
            color: '#2C3E50',
            accentColor: '#85929E',
            finColor: '#1B2631',
            pathType: 'float',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/whale.png',
            spawnDirections: ['left', 'right'],
            speedRange: [40, 80]
        },
        angelfish: {
            id: 'angelfish',
            name: '神仙鱼',
            score: 20,
            hp: 1,
            speed: 100,
            size: 44,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 22,
            color: '#E8E8E8',
            accentColor: '#1A1A2E',
            finColor: '#C0C0C0',
            pathType: 'sine',
            schoolFish: true,
            schoolSize: [3, 8],
            depth: 'near',
            imagePath: 'assets/fish/angelfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [70, 130]
        },
        betta: {
            id: 'betta',
            name: '斗鱼',
            score: 25,
            hp: 1,
            speed: 90,
            size: 40,
            boneSegments: 5,
            spineSegments: 8,
            fresnelIntensity: 0.13,
            scaleType: 'cycloid',
            spawnWeight: 18,
            color: '#E63946',
            accentColor: '#457B9D',
            finColor: '#C1121F',
            pathType: 'sine',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/betta.png',
            spawnDirections: ['left', 'right'],
            speedRange: [60, 110]
        },
        butterflyfish: {
            id: 'butterflyfish',
            name: '蝴蝶鱼',
            score: 40,
            hp: 2,
            speed: 110,
            size: 42,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'ctenoid',
            spawnWeight: 15,
            color: '#FFD60A',
            accentColor: '#000000',
            finColor: '#FFC300',
            pathType: 'sine',
            schoolFish: true,
            schoolSize: [2, 6],
            depth: 'mid',
            imagePath: 'assets/fish/butterflyfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [80, 140]
        },
        lionfish: {
            id: 'lionfish',
            name: '狮子鱼',
            score: 80,
            hp: 3,
            speed: 80,
            size: 52,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.12,
            scaleType: 'ctenoid',
            spawnWeight: 10,
            color: '#E07A5F',
            accentColor: '#FFFFFF',
            finColor: '#C94F38',
            pathType: 'float',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/lionfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [55, 100]
        },
        parrotfish: {
            id: 'parrotfish',
            name: '鹦鹉鱼',
            score: 60,
            hp: 3,
            speed: 100,
            size: 50,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.14,
            scaleType: 'ctenoid',
            spawnWeight: 12,
            color: '#2EC4B6',
            accentColor: '#F77F00',
            finColor: '#06A77D',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/parrotfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [70, 130]
        },
        tang: {
            id: 'tang',
            name: '蓝吊鱼',
            score: 50,
            hp: 2,
            speed: 120,
            size: 44,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.13,
            scaleType: 'ctenoid',
            spawnWeight: 14,
            color: '#0077B6',
            accentColor: '#FFD60A',
            finColor: '#023E8A',
            pathType: 'linear',
            schoolFish: true,
            schoolSize: [3, 8],
            depth: 'mid',
            imagePath: 'assets/fish/tang.png',
            spawnDirections: ['left', 'right'],
            speedRange: [90, 150]
        },
        red_arowana: {
            id: 'red_arowana',
            name: '红龙鱼',
            score: 200,
            hp: 8,
            speed: 130,
            size: 60,
            boneSegments: 7,
            spineSegments: 12,
            fresnelIntensity: 0.18,
            scaleType: 'ganoid',
            spawnWeight: 6,
            color: '#D62828',
            accentColor: '#FFBA08',
            finColor: '#9D0208',
            pathType: 'sine',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/red_arowana.png',
            spawnDirections: ['left', 'right'],
            speedRange: [100, 160]
        },
        luohan: {
            id: 'luohan',
            name: '罗汉鱼',
            score: 150,
            hp: 6,
            speed: 100,
            size: 52,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.15,
            scaleType: 'ctenoid',
            spawnWeight: 7,
            color: '#E63946',
            accentColor: '#FFD60A',
            finColor: '#6A040F',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/luohan.png',
            spawnDirections: ['left', 'right'],
            speedRange: [70, 120]
        },
        viperfish: {
            id: 'viperfish',
            name: '毒蛇鱼',
            score: 200,
            hp: 5,
            speed: 110,
            size: 48,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.15,
            scaleType: 'cycloid',
            spawnWeight: 6,
            color: '#0D1B2A',
            accentColor: '#06D6A0',
            finColor: '#1B263B',
            pathType: 'erratic',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/viperfish.png',
            glow: true,
            spawnDirections: ['left', 'right'],
            speedRange: [80, 140]
        },
        gulper_eel: {
            id: 'gulper_eel',
            name: '吞噬鳗',
            score: 180,
            hp: 5,
            speed: 80,
            size: 60,
            boneSegments: 7,
            spineSegments: 12,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 5,
            color: '#1A1A2E',
            accentColor: '#16213E',
            finColor: '#0F3460',
            pathType: 'float',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/gulper_eel.png',
            glow: true,
            spawnDirections: ['left', 'right'],
            speedRange: [50, 100]
        },
        giant_isopod: {
            id: 'giant_isopod',
            name: '巨型等足虫',
            score: 120,
            hp: 6,
            speed: 50,
            size: 50,
            boneSegments: 6,
            spineSegments: 9,
            fresnelIntensity: 0.10,
            scaleType: 'ganoid',
            spawnWeight: 7,
            color: '#6C757D',
            accentColor: '#ADB5BD',
            finColor: '#495057',
            pathType: 'random',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/giant_isopod.png',
            spawnDirections: ['left', 'right'],
            speedRange: [30, 60]
        },
        glass_squid: {
            id: 'glass_squid',
            name: '玻璃鱿鱼',
            score: 100,
            hp: 3,
            speed: 90,
            size: 44,
            boneSegments: 5,
            spineSegments: 8,
            fresnelIntensity: 0.15,
            scaleType: 'cycloid',
            spawnWeight: 8,
            color: '#A8DADC',
            accentColor: '#E0FBFC',
            finColor: '#457B9D',
            pathType: 'sine',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/glass_squid.png',
            spawnDirections: ['left', 'right'],
            speedRange: [60, 110]
        },
        dumbo_octopus: {
            id: 'dumbo_octopus',
            name: '小飞象章鱼',
            score: 150,
            hp: 3,
            speed: 70,
            size: 40,
            boneSegments: 5,
            spineSegments: 8,
            fresnelIntensity: 0.13,
            scaleType: 'cycloid',
            spawnWeight: 6,
            color: '#F8C4D8',
            accentColor: '#FFE5EC',
            finColor: '#F49AC2',
            pathType: 'float',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/dumbo_octopus.png',
            spawnDirections: ['left', 'right'],
            speedRange: [45, 85]
        },
        seadragon: {
            id: 'seadragon',
            name: '海龙',
            score: 80,
            hp: 2,
            speed: 60,
            size: 55,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 10,
            color: '#F4845F',
            accentColor: '#F7B267',
            finColor: '#E76F51',
            pathType: 'float',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/seadragon.png',
            spawnDirections: ['left', 'right'],
            speedRange: [40, 75]
        },
        leafy_seadragon: {
            id: 'leafy_seadragon',
            name: '叶海龙',
            score: 100,
            hp: 2,
            speed: 55,
            size: 55,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 8,
            color: '#B08900',
            accentColor: '#D4A017',
            finColor: '#8B6914',
            pathType: 'float',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/leafy_seadragon.png',
            spawnDirections: ['left', 'right'],
            speedRange: [35, 70]
        },
        sea_rabbit: {
            id: 'sea_rabbit',
            name: '海兔',
            score: 30,
            hp: 1,
            speed: 50,
            size: 28,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'cycloid',
            spawnWeight: 18,
            color: '#F1FAEE',
            accentColor: '#1D3557',
            finColor: '#A8DADC',
            pathType: 'float',
            schoolFish: true,
            schoolSize: [2, 5],
            depth: 'near',
            imagePath: 'assets/fish/sea_rabbit.png',
            spawnDirections: ['left', 'right'],
            speedRange: [35, 65]
        },
        sea_urchin: {
            id: 'sea_urchin',
            name: '海胆',
            score: 25,
            hp: 4,
            speed: 30,
            size: 36,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.10,
            scaleType: 'ganoid',
            spawnWeight: 15,
            color: '#4A1942',
            accentColor: '#6D3B7A',
            finColor: '#2D132C',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/sea_urchin.png',
            spawnDirections: ['left', 'right'],
            speedRange: [20, 40]
        },
        sea_cucumber: {
            id: 'sea_cucumber',
            name: '海参',
            score: 20,
            hp: 3,
            speed: 25,
            size: 44,
            boneSegments: 5,
            spineSegments: 8,
            fresnelIntensity: 0.08,
            scaleType: 'cycloid',
            spawnWeight: 15,
            color: '#C77B3F',
            accentColor: '#E09F3E',
            finColor: '#8B5A2B',
            pathType: 'random',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/sea_cucumber.png',
            spawnDirections: ['left', 'right'],
            speedRange: [15, 35]
        },
        sea_snake: {
            id: 'sea_snake',
            name: '海蛇',
            score: 100,
            hp: 4,
            speed: 120,
            size: 58,
            boneSegments: 7,
            spineSegments: 12,
            fresnelIntensity: 0.13,
            scaleType: 'cycloid',
            spawnWeight: 8,
            color: '#FFD60A',
            accentColor: '#000000',
            finColor: '#1B1B1B',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/sea_snake.png',
            spawnDirections: ['left', 'right'],
            speedRange: [90, 150]
        },
        flying_fish: {
            id: 'flying_fish',
            name: '飞鱼',
            score: 60,
            hp: 2,
            speed: 150,
            size: 44,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.14,
            scaleType: 'ctenoid',
            spawnWeight: 12,
            color: '#8ECAE6',
            accentColor: '#219EBC',
            finColor: '#023047',
            pathType: 'linear',
            schoolFish: true,
            schoolSize: [2, 5],
            depth: 'mid',
            imagePath: 'assets/fish/flying_fish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [120, 180]
        },
        archerfish: {
            id: 'archerfish',
            name: '射水鱼',
            score: 45,
            hp: 2,
            speed: 100,
            size: 40,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 15,
            color: '#C9D6DF',
            accentColor: '#000000',
            finColor: '#8D99AE',
            pathType: 'sine',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/archerfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [75, 125]
        },
        hatchetfish: {
            id: 'hatchetfish',
            name: '斧头鱼',
            score: 80,
            hp: 1,
            speed: 90,
            size: 32,
            boneSegments: 4,
            spineSegments: 8,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 10,
            color: '#B8D4E3',
            accentColor: '#E0FBFC',
            finColor: '#5FA8D3',
            pathType: 'sine',
            schoolFish: true,
            schoolSize: [3, 8],
            depth: 'far',
            imagePath: 'assets/fish/hatchetfish.png',
            glow: true,
            spawnDirections: ['left', 'right'],
            speedRange: [65, 110]
        },
        barreleye: {
            id: 'barreleye',
            name: '管眼鱼',
            score: 150,
            hp: 3,
            speed: 70,
            size: 44,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.15,
            scaleType: 'cycloid',
            spawnWeight: 6,
            color: '#1B4332',
            accentColor: '#52B788',
            finColor: '#081C15',
            pathType: 'float',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/barreleye.png',
            glow: true,
            spawnDirections: ['left', 'right'],
            speedRange: [50, 85]
        },
        moray_eel: {
            id: 'moray_eel',
            name: '海鳗',
            score: 90,
            hp: 5,
            speed: 100,
            size: 65,
            boneSegments: 7,
            spineSegments: 12,
            fresnelIntensity: 0.12,
            scaleType: 'cycloid',
            spawnWeight: 9,
            color: '#D4A017',
            accentColor: '#6B4F00',
            finColor: '#8B6914',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/moray_eel.png',
            spawnDirections: ['left', 'right'],
            speedRange: [75, 130]
        },
        stingray: {
            id: 'stingray',
            name: '黄貂鱼',
            score: 120,
            hp: 5,
            speed: 90,
            size: 60,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.12,
            scaleType: 'ctenoid',
            spawnWeight: 8,
            color: '#8B7355',
            accentColor: '#B09A7A',
            finColor: '#5D4E37',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/stingray.png',
            imageScale: 2.0,
            spawnDirections: ['left', 'right'],
            speedRange: [65, 115]
        },
        nautilus: {
            id: 'nautilus',
            name: '鹦鹉螺',
            score: 130,
            hp: 4,
            speed: 60,
            size: 48,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.13,
            scaleType: 'ganoid',
            spawnWeight: 7,
            color: '#D4A574',
            accentColor: '#8B4513',
            finColor: '#A0522D',
            pathType: 'float',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/nautilus.png',
            spawnDirections: ['left', 'right'],
            speedRange: [40, 75]
        },
        cuttlefish: {
            id: 'cuttlefish',
            name: '墨鱼',
            score: 70,
            hp: 3,
            speed: 100,
            size: 44,
            boneSegments: 5,
            spineSegments: 9,
            fresnelIntensity: 0.13,
            scaleType: 'cycloid',
            spawnWeight: 10,
            color: '#B07D4F',
            accentColor: '#D4A574',
            finColor: '#6B4226',
            pathType: 'sine',
            schoolFish: false,
            depth: 'mid',
            imagePath: 'assets/fish/cuttlefish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [75, 125]
        },
        manatee: {
            id: 'manatee',
            name: '海牛',
            score: 300,
            hp: 15,
            speed: 50,
            size: 90,
            boneSegments: 7,
            spineSegments: 11,
            fresnelIntensity: 0.15,
            scaleType: 'ctenoid',
            spawnWeight: 4,
            color: '#6C757D',
            accentColor: '#ADB5BD',
            finColor: '#495057',
            pathType: 'float',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/manatee.png',
            spawnDirections: ['left', 'right'],
            speedRange: [35, 65]
        },
        koi: {
            id: 'koi',
            name: '锦鲤',
            score: 80,
            hp: 4,
            speed: 80,
            size: 52,
            boneSegments: 6,
            spineSegments: 10,
            fresnelIntensity: 0.14,
            scaleType: 'cycloid',
            spawnWeight: 10,
            color: '#E63946',
            accentColor: '#FFFFFF',
            finColor: '#F4A261',
            pathType: 'sine',
            schoolFish: false,
            depth: 'near',
            imagePath: 'assets/fish/koi.png',
            spawnDirections: ['left', 'right'],
            speedRange: [55, 100]
        },
        oarfish: {
            id: 'oarfish',
            name: '皇带鱼',
            score: 500,
            hp: 15,
            speed: 70,
            size: 100,
            boneSegments: 8,
            spineSegments: 12,
            fresnelIntensity: 0.18,
            scaleType: 'ctenoid',
            spawnWeight: 3,
            color: '#C0C8D0',
            accentColor: '#D62828',
            finColor: '#8A0303',
            pathType: 'sine',
            schoolFish: false,
            depth: 'far',
            imagePath: 'assets/fish/oarfish.png',
            spawnDirections: ['left', 'right'],
            speedRange: [50, 90]
        }
    },

    // ===== 生成权重（按关卡难度调整） =====
    getSpawnList(level = 1) {
        const list = [];
        const difficulty = Math.min(level / 20, 1); // 难度系数 0-1

        for (const [id, fish] of Object.entries(this.types)) {
            let weight = fish.spawnWeight;
            // 高关卡增加高价值鱼出现概率
            if (fish.score >= 200) {
                weight *= (1 + difficulty * 0.5);
            }
            // 低关卡减少高价值鱼
            if (fish.score >= 500 && level < 5) {
                weight *= 0.3;
            }
            list.push({ id, weight });
        }
        return list;
    },

    // ===== 鱼群配置 =====
    school: {
        spawnInterval: 3,                // 鱼群生成间隔（秒）
        maxSchools: 5,                    // 最大同时鱼群数
        separationDistance: 40,           // 分离距离
        alignmentDistance: 80,            // 对齐距离
        cohesionDistance: 120,            // 凝聚距离
        maxSpeed: 150,                    // 最大速度
        maxForce: 0.5                     // 最大转向力
    },

    // ===== AI 行为 =====
    ai: {
        dodgeRadius: 150,                 // 躲避炮弹半径
        dodgeSpeedMultiplier: 1.8,        // 躲避时速度倍率
        bossDisperseSpeed: 250,           // BOSS 驱散时小鱼速度
        wanderChangeInterval: 2,           // 随机游走方向变化间隔
        turnSpeed: 2                        // 转向速度（弧度/秒）
    },

    // ===== 骨骼动画参数 =====
    boneAnimation: {
        bodyWaveFrequency: 3,              // 身体摆动频率
        bodyWaveAmplitude: 0.15,           // 身体摆动幅度（弧度）
        tailFrequency: 6,                   // 尾鳍扇动频率
        tailAmplitude: 0.4,                 // 尾鳍扇动幅度
        finFrequency: 4,                    // 胸鳍扇动频率
        finAmplitude: 0.3,                  // 胸鳍扇动幅度
        speedInfluence: 0.5,                // 速度对动画频率的影响
        // 脊椎分段摆动幅度权重：头/躯干/尾
        headAmpScale: 0.3,                  // 头部摆动幅度系数
        tailAmpScale: 1.5                   // 尾部摆动幅度系数
    },

    // ===== 动画状态机（7 种状态）=====
    // freq/amp 为相对 boneAnimation 的倍率；bendMult 为身体弯曲度倍率
    animStates: {
        idle:   { freq: 0.5, bodyAmp: 0.6, tailFreq: 0.5, tailAmp: 0.5, finFreq: 0.4, finAmp: 0.6, bendMult: 0.7 },
        swim:   { freq: 1.0, bodyAmp: 1.0, tailFreq: 1.0, tailAmp: 1.0, finFreq: 1.0, finAmp: 1.0, bendMult: 1.0 },
        fast:   { freq: 1.5, bodyAmp: 1.2, tailFreq: 1.8, tailAmp: 1.5, finFreq: 1.4, finAmp: 1.2, bendMult: 1.5 },
        turn:   { freq: 1.0, bodyAmp: 1.3, tailFreq: 1.2, tailAmp: 1.2, finFreq: 1.6, finAmp: 1.4, bendMult: 1.4 },
        escape: { freq: 2.0, bodyAmp: 1.6, tailFreq: 2.5, tailAmp: 1.8, finFreq: 2.0, finAmp: 1.5, bendMult: 1.6 },
        hurt:   { freq: 3.0, bodyAmp: 0.3, tailFreq: 3.0, tailAmp: 0.3, finFreq: 2.0, finAmp: 0.5, bendMult: 0.5 },
        dying:  { freq: 0.3, bodyAmp: 0.2, tailFreq: 0.4, tailAmp: 0.2, finFreq: 0.3, finAmp: 0.2, bendMult: 0.5 }
    },

    // ===== 状态切换阈值 =====
    stateRules: {
        fastSpeedRatio: 1.3,                // 速度 > baseSpeed*1.3 → fast
        idleSpeedRatio: 0.5,                // 速度 < baseSpeed*0.5 → idle
        turnRadPerSec: 6.0,                 // 方向变化速率 > 此值(rad/s) → turn
        hurtDuration: 0.3                    // 受击僵直时长（秒）
    },

    // ===== 鱼鳍 Verlet 物理参数 =====
    physics: {
        damping: 0.85,                      // 阻尼（水阻力）
        iterations: 3,                      // 约束求解迭代次数
        bodyStiffness: 0.9,                 // 鱼身刚度
        finStiffness: 0.3,                  // 鱼鳍刚度（柔性）
        headMass: 1.5,                      // 鱼头质量（重）
        tailMass: 0.5,                      // 鱼尾质量（轻）
        pectoralNodes: 3,                   // 每侧胸鳍边缘节点数
        dorsalNodes: 6,                     // 背鳍边缘节点数
        tailLobeNodes: 4,                   // 尾鳍每叶边缘节点数
        waterForceX: 0.6,                   // 沿游向反向的水流阻力
        turbulenceY: 1.2                    // 垂直水流扰动幅度
    },

    // ===== 生成系统配置 =====
    spawnSystem: {
        minInterval: 0.3,                   // 最小生成间隔（秒）
        maxInterval: 0.8,                    // 最大生成间隔（秒）
        schoolChance: 0.45,                  // 结群鱼类生成鱼群的概率
        maxFishPerSpawn: 8,                 // 单次最多生成鱼数
        outOfBoundsMargin: 100,              // 出框判定边距（像素）
    },

    // ===== 炮弹反弹配置 =====
    bulletBounce: {
        maxBounces: 3,                       // 最大反弹次数
        speedDecay: 0.9,                     // 反弹后速度衰减倍率
        bounceScalePulse: 1.3,               // 反弹时缩放脉冲
        bounceParticleCount: 8               // 反弹水花粒子数
    }
};
